package com.bancosantander.reglasnegociotc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class inputGlobales implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer limiteInferior;
	private java.lang.Integer limiteObjetivo;
	private java.lang.Integer minimoCompra;

	public inputGlobales() {
	}

	public java.lang.Integer getLimiteInferior() {
		return this.limiteInferior;
	}

	public void setLimiteInferior(java.lang.Integer limiteInferior) {
		this.limiteInferior = limiteInferior;
	}

	public java.lang.Integer getLimiteObjetivo() {
		return this.limiteObjetivo;
	}

	public void setLimiteObjetivo(java.lang.Integer limiteObjetivo) {
		this.limiteObjetivo = limiteObjetivo;
	}

	public java.lang.Integer getMinimoCompra() {
		return this.minimoCompra;
	}

	public void setMinimoCompra(java.lang.Integer minimoCompra) {
		this.minimoCompra = minimoCompra;
	}

	public inputGlobales(java.lang.Integer limiteInferior,
			java.lang.Integer limiteObjetivo, java.lang.Integer minimoCompra) {
		this.limiteInferior = limiteInferior;
		this.limiteObjetivo = limiteObjetivo;
		this.minimoCompra = minimoCompra;
	}

}