package com.bancosantander.reglasnegociotc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class inputPeriodoAnterior implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer pagoMinimoTc;

	private java.lang.String pagoRecurrente;

	private java.lang.String nomina;

	private java.lang.String asistenciaContrat;

	private java.lang.String domiciliada;

	public inputPeriodoAnterior() {
	}

	public java.lang.Integer getPagoMinimoTc() {
		return this.pagoMinimoTc;
	}

	public void setPagoMinimoTc(java.lang.Integer pagoMinimoTc) {
		this.pagoMinimoTc = pagoMinimoTc;
	}

	public java.lang.String getPagoRecurrente() {
		return this.pagoRecurrente;
	}

	public void setPagoRecurrente(java.lang.String pagoRecurrente) {
		this.pagoRecurrente = pagoRecurrente;
	}

	public java.lang.String getNomina() {
		return this.nomina;
	}

	public void setNomina(java.lang.String nomina) {
		this.nomina = nomina;
	}

	public java.lang.String getAsistenciaContrat() {
		return this.asistenciaContrat;
	}

	public void setAsistenciaContrat(java.lang.String asistenciaContrat) {
		this.asistenciaContrat = asistenciaContrat;
	}

	public java.lang.String getDomiciliada() {
		return this.domiciliada;
	}

	public void setDomiciliada(java.lang.String domiciliada) {
		this.domiciliada = domiciliada;
	}

	public inputPeriodoAnterior(java.lang.Integer pagoMinimoTc,
			java.lang.String pagoRecurrente, java.lang.String nomina,
			java.lang.String asistenciaContrat, java.lang.String domiciliada) {
		this.pagoMinimoTc = pagoMinimoTc;
		this.pagoRecurrente = pagoRecurrente;
		this.nomina = nomina;
		this.asistenciaContrat = asistenciaContrat;
		this.domiciliada = domiciliada;
	}

}