package com.bancosantander.reglasnegociotc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class inputPeriodoActual implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer montoAcumulado;
	private java.lang.Integer pagoTc;
	private java.util.Date fechaPago;
	private java.util.Date fechaLimitePago;

	private java.lang.String tcDomiciliada;

	private java.lang.String pagoRecurrente;

	private java.lang.String nomina;

	private java.lang.String asistentContratada;

	public inputPeriodoActual() {
	}

	public java.lang.Integer getMontoAcumulado() {
		return this.montoAcumulado;
	}

	public void setMontoAcumulado(java.lang.Integer montoAcumulado) {
		this.montoAcumulado = montoAcumulado;
	}

	public java.lang.Integer getPagoTc() {
		return this.pagoTc;
	}

	public void setPagoTc(java.lang.Integer pagoTc) {
		this.pagoTc = pagoTc;
	}

	public java.util.Date getFechaPago() {
		return this.fechaPago;
	}

	public void setFechaPago(java.util.Date fechaPago) {
		this.fechaPago = fechaPago;
	}

	public java.util.Date getFechaLimitePago() {
		return this.fechaLimitePago;
	}

	public void setFechaLimitePago(java.util.Date fechaLimitePago) {
		this.fechaLimitePago = fechaLimitePago;
	}

	public java.lang.String getTcDomiciliada() {
		return this.tcDomiciliada;
	}

	public void setTcDomiciliada(java.lang.String tcDomiciliada) {
		this.tcDomiciliada = tcDomiciliada;
	}

	public java.lang.String getPagoRecurrente() {
		return this.pagoRecurrente;
	}

	public void setPagoRecurrente(java.lang.String pagoRecurrente) {
		this.pagoRecurrente = pagoRecurrente;
	}

	public java.lang.String getNomina() {
		return this.nomina;
	}

	public void setNomina(java.lang.String nomina) {
		this.nomina = nomina;
	}

	public java.lang.String getAsistentContratada() {
		return this.asistentContratada;
	}

	public void setAsistentContratada(java.lang.String asistentContratada) {
		this.asistentContratada = asistentContratada;
	}

	public inputPeriodoActual(java.lang.Integer montoAcumulado,
			java.lang.Integer pagoTc, java.util.Date fechaPago,
			java.util.Date fechaLimitePago, java.lang.String tcDomiciliada,
			java.lang.String pagoRecurrente, java.lang.String nomina,
			java.lang.String asistentContratada) {
		this.montoAcumulado = montoAcumulado;
		this.pagoTc = pagoTc;
		this.fechaPago = fechaPago;
		this.fechaLimitePago = fechaLimitePago;
		this.tcDomiciliada = tcDomiciliada;
		this.pagoRecurrente = pagoRecurrente;
		this.nomina = nomina;
		this.asistentContratada = asistentContratada;
	}

}