package com.bancosantander.reglasnegociotc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InputRegla1 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer montoAcumulado;
	public InputRegla1() {
	}

	public java.lang.Integer getMontoAcumulado() {
		return this.montoAcumulado;
	}

	public void setMontoAcumulado(java.lang.Integer montoAcumulado) {
		this.montoAcumulado = montoAcumulado;
	}

	public InputRegla1(java.lang.Integer montoAcumulado) {
		this.montoAcumulado = montoAcumulado;
	}

}