package com.bancosantander.reglasnegociotc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OutputRegla1 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String acumulado;

	public OutputRegla1() {
	}

	public java.lang.String getAcumulado() {
		return this.acumulado;
	}

	public void setAcumulado(java.lang.String acumulado) {
		this.acumulado = acumulado;
	}

	public OutputRegla1(java.lang.String acumulado) {
		this.acumulado = acumulado;
	}

}