package com.bancosantander.likeu.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DatosProceso implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.Date activation_date;
	private java.lang.String type;
	private java.lang.String status;
	private java.util.Date cut_of_date;
	private com.bancosantander.likeu.model.CardDetail card;

	public DatosProceso() {
	}
	@Override
	public java.util.Date getActivation_date() {
		return this.activation_date;
	}
	@Override
	public void setActivation_date(java.util.Date activation_date) {
		this.activation_date = activation_date;
	}
	@Override
	public java.lang.String getType() {
		return this.type;
	}
	@Override
	public void setType(java.lang.String type) {
		this.type = type;
	}
	@Override
	public java.lang.String getStatus() {
		return this.status;
	}
	@Override
	public void setStatus(java.lang.String status) {
		this.status = status;
	}
	@Override
	public java.util.Date getCut_of_date() {
		return this.cut_of_date;
	}
	@Override
	public void setCut_of_date(java.util.Date cut_of_date) {
		this.cut_of_date = cut_of_date;
	}
	@Override
	public com.bancosantander.likeu.model.CardDetail getCard() {
		return this.card;
	}
	@Override
	public void setCard(com.bancosantander.likeu.model.CardDetail card) {
		this.card = card;
	}
	@Override
	public DatosProceso(java.util.Date activation_date, java.lang.String type,
			java.lang.String status, java.util.Date cut_of_date,
			com.bancosantander.likeu.model.CardDetail card) {
		this.activation_date = activation_date;
		this.type = type;
		this.status = status;
		this.cut_of_date = cut_of_date;
		this.card = card;
	}

}